Griffin.FrameworkWeb/Controllers/DocController.cs
using System;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Mvc;
using GriffinFrameworkWeb.Infrastructure;

namespace GriffinFrameworkWeb.Controllers
{
    public class DocController : Controller
    {
        [Route("doc/{*path}"), HttpGet]
        public ActionResult Index(string path)
        {
            var folderPath = string.IsNullOrEmpty(ConfigurationManager.AppSettings["DocPath"])
                ? Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "DocPages")
                : ConfigurationManager.AppSettings["DocPath"];

            var parser = new Parser(folderPath, Url.Content("~/doc/"));

            //must include doc for all pages to render links correctly
            var html = parser.ParseUrl("doc/" + path);

            return View("Index", (object)html);
        }

        public ActionResult Image(string src)
        {
            var folderPath = string.IsNullOrEmpty(ConfigurationManager.AppSettings["DocPath"])
                ? Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "DocPages")
                : ConfigurationManager.AppSettings["DocPath"];

            var mime = MimeMapping.GetMimeMapping(Path.GetFileName(src));

            return File(Path.Combine(folderPath, src.Replace("/", "\\")), mime);
        }
    }
}

Griffin.FrameworkWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content=".net, c#, data mapper, application library, .net networking, c# sockets">
    <meta name="description" content="A .NET application library to build applications faster. Includes a data mapper, netwokring, http etc.">
    <meta name="author" content="Gauffin Interactive AB" />
    <title>Griffin Framework</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/prism.css")" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Content("~/")">Griffin Framework</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="@if (Request.Path == Url.Action("Index", "Home")) { <text>active</text> }">
                        <a href="@Url.Content("~/")">Home</a>
                    </li>
                    <li class="@if (Request.Path == Url.Action("Index", "Doc")) { <text>active</text> }">
                        <a href="@Url.Content("~/doc")">Documentation</a>
                    </li>
                    <li><a href="http://twitter.com/jgauffin">Twitter</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>
    @RenderBody()
    <div class="container clearfix">
        &nbsp;
    </div>
    <!-- /.container -->
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/prism.min.js")"></script>
</body>
</html>